const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Pin,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Keyboard,
		C3.Plugins.Touch,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Behaviors.Platform,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Text.Acts.SetFontColor,
		C3.Plugins.Text.Acts.SetFontSize,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Plugins.Mouse.Cnds.OnClick
	];
};
self.C3_JsPropNameTable = [
	{Pin: 0},
	{dino: 0},
	{background: 0},
	{txtTexto: 0},
	{txtButtonplay: 0},
	{Mouse: 0},
	{Keyboard: 0},
	{Touch: 0},
	{ground: 0},
	{dinoRun: 0},
	{Solid: 0},
	{groundcollider: 0},
	{dinoDead: 0},
	{Platform: 0},
	{player: 0},
	{enemy: 0},
	{enemydestroy: 0},
	{Text: 0},
	{txtScore: 0},
	{backgroundMovement: 0},
	{groundMovement: 0},
	{score: 0},
	{isDead: 0}
];

self.InstanceType = {
	dino: class extends self.ISpriteInstance {},
	background: class extends self.ISpriteInstance {},
	txtTexto: class extends self.ITextInstance {},
	txtButtonplay: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	ground: class extends self.ITiledBackgroundInstance {},
	dinoRun: class extends self.ISpriteInstance {},
	groundcollider: class extends self.ISpriteInstance {},
	dinoDead: class extends self.ISpriteInstance {},
	player: class extends self.ISpriteInstance {},
	enemy: class extends self.ISpriteInstance {},
	enemydestroy: class extends self.ISpriteInstance {},
	Text: class extends self.ITextInstance {},
	txtScore: class extends self.ITextInstance {}
}